export const columns = [
    {
        label: 'Varázslat', name: 'spell'
    },
    { label: 'Mp', name: 'mp' },
    { label: 'E', name: 'e' },
    { label: '+E/Mp', name: 'emp' },
    { label: 'Varázslás Ideje', name: 'cast_time' },
    { label: 'Időtartam', name: 'duration' },
    { label: 'Hatótáv', name: 'range' },
    { label: 'ME Típusa', name: 'me_type' },
    { label: 'Arkánum', name: 'arcanum' },
    { label: 'Típus', name: 'type' },
    {
        label: 'Szféra',
        name: 'sphere',
        lookup: {
            "Általános": "Általános",
            "Halál": "Halál",
            "Élet": "Élet",
            "Lélek": "Lélek",
            "Természet": "Természet"
        },
    },
];

export const magusData = [
    {
        "spell": "Érzékelés-mágia",
        "mp": 1,
        "e": 1,
        "emp": "1/1",
        "cast_time": "1k",
        "duration": "1perc/2Tsz",
        "range": "20m",
        "me_type": "Leplezés",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Mágia kifürkészése",
        "mp": 1,
        "e": 1,
        "emp": "1/1",
        "cast_time": "5sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Leplezés",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Mágia szétoszlatása",
        "mp": 1,
        "e": 1,
        "emp": "1/1",
        "cast_time": "1k",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Mágia mp-je",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Leplezés",
        "mp": 1,
        "e": 1,
        "emp": "1/1",
        "cast_time": "+1k",
        "duration": "Varázslaté",
        "range": "varázslat",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Áldás",
        "mp": 3,
        "e": 5,
        "emp": "-",
        "cast_time": "5sz",
        "duration": "1hónap/Tsz",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Ima",
        "mp": 3,
        "e": 5,
        "emp": "-",
        "cast_time": "3sz",
        "duration": "2kör/Tsz*",
        "range": "20m",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Szent fény",
        "mp": 3,
        "e": 15,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "1perc/Tsz*",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "A hatalom szava",
        "mp": 15,
        "e": 35,
        "emp": "2/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "30m",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Rendreutasítás",
        "mp": 2,
        "e": 25,
        "emp": "3/1",
        "cast_time": "1sz",
        "duration": "",
        "range": "20m",
        "me_type": "mentális",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "Szertartás",
        "mp": 3,
        "e": 1,
        "emp": "-",
        "cast_time": "változó",
        "duration": "Maradandó",
        "range": "Változó",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "Aszkézis",
        "mp": 9,
        "e": 1,
        "emp": "-",
        "cast_time": "1 ó",
        "duration": "1 nap",
        "range": "önmaga",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "Hit hatalma",
        "mp": 9,
        "e": 1,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "",
        "range": "önmaga",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "Transz",
        "mp": 18,
        "e": 1,
        "emp": "-",
        "cast_time": "1ó",
        "duration": "Egyszeri",
        "range": "önmaga",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "Varázstárgy készítés",
        "mp": "Változó",
        "e": "",
        "emp": "",
        "cast_time": "",
        "duration": "",
        "range": "",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Érzékelés-átok",
        "mp": 13,
        "e": 25,
        "emp": "1/1",
        "cast_time": "1p",
        "duration": "Egyszeri",
        "range": "érintés",
        "me_type": "x",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Feloldozás",
        "mp": 30,
        "e": 20,
        "emp": "-",
        "cast_time": "1k",
        "duration": "Spec.",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Kárhozat",
        "mp": 30,
        "e": 1,
        "emp": "-",
        "cast_time": "1k",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Kiátkozás",
        "mp": 30,
        "e": 20,
        "emp": "-",
        "cast_time": "1k",
        "duration": "Maradandó",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Űzés-átok",
        "mp": 35,
        "e": 10,
        "emp": "1/1",
        "cast_time": "",
        "duration": "Egyszeri",
        "range": "Éintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Általános"
    },
    {
        "spell": "Isteni áldás",
        "mp": 90,
        "e": 25,
        "emp": "1/2",
        "cast_time": "3sz",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "Külső síkok lényeinek megidézése",
        "mp": 80,
        "e": 1,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "Speciális",
        "range": "-",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "Audiencia",
        "mp": 200,
        "e": 1,
        "emp": "-",
        "cast_time": "1ó",
        "duration": "Változó",
        "range": "Önmaga",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "Istenek hona",
        "mp": 320,
        "e": 1,
        "emp": "-",
        "cast_time": "3ó",
        "duration": "1perc",
        "range": "20m",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Általános"
    },
    {
        "spell": "A halál érintése",
        "mp": 4,
        "e": 1,
        "emp": "1/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Életerő",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Méregérzékelés",
        "mp": 5,
        "e": 15,
        "emp": "1/1",
        "cast_time": "2k",
        "duration": "Egyszeri",
        "range": "5m",
        "me_type": "Lepl E",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Vérgyűjtés",
        "mp": 5,
        "e": 1,
        "emp": "-",
        "cast_time": "3sz",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Méreg elkészítése",
        "mp": 8,
        "e": 1,
        "emp": "-",
        "cast_time": "10p",
        "duration": "Egyszeri",
        "range": "érintés",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Vámpírok öröksége",
        "mp": 8,
        "e": 1,
        "emp": "-",
        "cast_time": "3k",
        "duration": "5perc/Tsz",
        "range": "Önmaga",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Káoszkard",
        "mp": 10,
        "e": 1,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "3kör/Tsz*",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Láthatatlanság túlvilági lények elől",
        "mp": 10,
        "e": 5,
        "emp": "2/1",
        "cast_time": "2sz",
        "duration": "5perc/Tsz",
        "range": "Érintés",
        "me_type": "láthatatlanság",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Védekezés a „jótól”",
        "mp": 15,
        "e": 20,
        "emp": "3/1",
        "cast_time": "1k",
        "duration": "3k/Tsz",
        "range": "15m",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Időtlen álom",
        "mp": 18,
        "e": 5,
        "emp": "2/1",
        "cast_time": "1p",
        "duration": "Spec.",
        "range": "Érintés",
        "me_type": "Mentális",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Mérgek erősítése",
        "mp": "Spec.",
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "1nap/2Tsz",
        "range": "érintés",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Életerő csapolás",
        "mp": "1Fp/1mp(1szegmens)",
        "e": "",
        "emp": "",
        "cast_time": "",
        "duration": "",
        "range": "",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "1Ép/2mp(5szegmens)",
        "mp": "",
        "e": "",
        "emp": "",
        "cast_time": "Egyszeri",
        "duration": "érintés",
        "range": "Életerő",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Vérből sav",
        "mp": 6,
        "e": 1,
        "emp": "-",
        "cast_time": "1k",
        "duration": "Egyszeri",
        "range": "5m",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Vérzés",
        "mp": 7,
        "e": 2,
        "emp": "5/1",
        "cast_time": "1sz",
        "duration": "1kör/Tsz",
        "range": "20m",
        "me_type": "Egészség",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Véráldozat",
        "mp": 10,
        "e": 1,
        "emp": "1/1",
        "cast_time": "3sz",
        "duration": "2perc/Tsz",
        "range": "20m",
        "me_type": "Egészség",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Vérgát",
        "mp": 18,
        "e": 1,
        "emp": "-",
        "cast_time": "3p",
        "duration": "1nap/Tsz",
        "range": "Érintés",
        "me_type": "Spec.",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Intő jel",
        "mp": 25,
        "e": 3,
        "emp": "2/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Mérgezés",
        "mp": "Spec.",
        "e": "Spec",
        "emp": "Spec",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "Érintés",
        "me_type": "Egészség",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "A halál lehelete",
        "mp": 6,
        "e": 1,
        "emp": "6/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "1m/Tsz",
        "me_type": "Életerő",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Izzó vér",
        "mp": 9,
        "e": 2,
        "emp": "6/1",
        "cast_time": "3sz",
        "duration": "2kör/Tsz",
        "range": "20m",
        "me_type": "Egészség",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Holttá válás",
        "mp": 10,
        "e": 1,
        "emp": "-",
        "cast_time": "6k",
        "duration": "10perc/Tsz*",
        "range": "Önmaga",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Vérdermesztés",
        "mp": 10,
        "e": 1,
        "emp": "8/1",
        "cast_time": "3sz",
        "duration": "1kör/Tsz",
        "range": "20m",
        "me_type": "Egészség",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Mérgező lehelet",
        "mp": 13,
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "1óra/Tsz",
        "range": "Önmaga",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Esszencia elrablása",
        "mp": 15,
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "1óra/Tsz",
        "range": "Önmaga",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Holtak megelevenítése",
        "mp": 20,
        "e": 1,
        "emp": "-",
        "cast_time": "1k",
        "duration": "5perc/Tsz",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Átok",
        "mp": 25,
        "e": 1,
        "emp": "1/1",
        "cast_time": "Spec.",
        "duration": "Maradandó",
        "range": "20m",
        "me_type": "Egészség",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "A halál szava",
        "mp": 40,
        "e": 5,
        "emp": "2/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Asztrál",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Halálelementál idézése",
        "mp": 50,
        "e": 1,
        "emp": "-",
        "cast_time": "10k",
        "duration": "1perc/Tsz",
        "range": "3m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Halál"
    },
    {
        "spell": "Kitörlés",
        "mp": 20,
        "e": 1,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Speciális",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Lélekcsapda",
        "mp": 35,
        "e": 1,
        "emp": "-",
        "cast_time": "1k",
        "duration": "5év/Tsz*",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Lélekáldozat",
        "mp": 45,
        "e": 10,
        "emp": "4/1",
        "cast_time": "2p",
        "duration": "Egyszeri",
        "range": "Érintés",
        "me_type": "Asztrál",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Eggyé válás",
        "mp": 65,
        "e": 1,
        "emp": "-",
        "cast_time": "1ó",
        "duration": "Egyszeri",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Gólem teremtés (halál)",
        "mp": 80,
        "e": 1,
        "emp": "-",
        "cast_time": "1n",
        "duration": "Maradandó",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Pestis",
        "mp": 90,
        "e": 1,
        "emp": "-",
        "cast_time": "10p",
        "duration": "Spec.",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Átkozott föld",
        "mp": 110,
        "e": 110,
        "emp": "1/1",
        "cast_time": "1n",
        "duration": "Maradandó",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Vérgólem készítése",
        "mp": 155,
        "e": 1,
        "emp": "-",
        "cast_time": "20p",
        "duration": "Maradandó",
        "range": "",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "rituáléi",
        "sphere": "Halál"
    },
    {
        "spell": "Sebvizsgálat",
        "mp": "0*",
        "e": "-",
        "emp": "-",
        "cast_time": "1 kör",
        "duration": "egyszeri",
        "range": "kézfölététel",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Gyógyítás",
        "mp": "3Fp - 1 mp",
        "e": "",
        "emp": "",
        "cast_time": "",
        "duration": "",
        "range": "",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Mérgezés",
        "mp": 35,
        "e": "8 kör",
        "emp": "egyszeri",
        "cast_time": "érintés",
        "duration": "-",
        "range": "",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Élet érzékékelése",
        "mp": 2,
        "e": 5,
        "emp": "-",
        "cast_time": "2k",
        "duration": "1kör/Tsz",
        "range": "30m",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Tisztító tűz",
        "mp": 4,
        "e": 1,
        "emp": "1/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Méregérzékelés",
        "mp": 5,
        "e": 15,
        "emp": "1/1",
        "cast_time": "2k",
        "duration": "Egyszeri",
        "range": "5m",
        "me_type": "Lepl E",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Élelemteremtés",
        "mp": 7,
        "e": 1,
        "emp": "-",
        "cast_time": "1k",
        "duration": "Egyszeri",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Láthatatlanság túlvilági lények elől",
        "mp": 10,
        "e": 5,
        "emp": "2/1",
        "cast_time": "2sz",
        "duration": "5perc/Tsz",
        "range": "Érintés",
        "me_type": "Láthatatlanság",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Láthatatlanság evilági lények elől",
        "mp": 10,
        "e": 5,
        "emp": "2/1",
        "cast_time": "2sz",
        "duration": "5perc/Tsz",
        "range": "Érintés",
        "me_type": "Láthatatlanság",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Óvó pajzs",
        "mp": 10,
        "e": 1,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "3kör/Tsz*",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Védekezés a „gonosztól”",
        "mp": 15,
        "e": 10,
        "emp": "3/2",
        "cast_time": "1k",
        "duration": "3k/Tsz",
        "range": "10m",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Méreg elpusztítása",
        "mp": 2,
        "e": 1,
        "emp": "",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "5m",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Az élet szentsége",
        "mp": 2,
        "e": 5,
        "emp": "1/1",
        "cast_time": "3sz",
        "duration": "1óra/Tsz",
        "range": "20m",
        "me_type": "Asztrál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Termékenység",
        "mp": 3,
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "1nap/Tsz",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Életpajzs",
        "mp": 6,
        "e": 1,
        "emp": "1/1",
        "cast_time": "1sz",
        "duration": "3kör/Tsz",
        "range": "20m",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Elmúlt életek",
        "mp": 6,
        "e": 10,
        "emp": "1/2",
        "cast_time": "1p",
        "duration": "1perc",
        "range": "20m",
        "me_type": "Mentál és Asztrál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Fájdalomcsillapítás",
        "mp": 7,
        "e": 25,
        "emp": "1/2",
        "cast_time": "1p",
        "duration": "1óra/Tsz",
        "range": "Érintés",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Védelem a betegségektől",
        "mp": 10,
        "e": 1,
        "emp": "-",
        "cast_time": "2k",
        "duration": "5perc/Tsz",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Védelem a mérgektől",
        "mp": 10,
        "e": 1,
        "emp": "-",
        "cast_time": "2k",
        "duration": "5perc/Tsz",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Őrző aura",
        "mp": 20,
        "e": 25,
        "emp": "1/1",
        "cast_time": "1p",
        "duration": "1óra/Tsz",
        "range": "Érintés",
        "me_type": "Mentál",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Segélykérés",
        "mp": "Spec.",
        "e": 25,
        "emp": "1/1",
        "cast_time": "spec",
        "duration": "Speciális",
        "range": "Speciális",
        "me_type": "Térmágia és Szimpatikus",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Gyóntatás",
        "mp": 6,
        "e": 1,
        "emp": "-",
        "cast_time": "5p",
        "duration": "4nap",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Halálon túli védelem",
        "mp": 10,
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "1nap/Tsz",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Regeneráció",
        "mp": 15,
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "1óra/Tsz*",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Védelem a holtaktól",
        "mp": 15,
        "e": 1,
        "emp": "-",
        "cast_time": "3sz",
        "duration": "5perc/Tsz",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Összetartozás életerővel",
        "mp": 30,
        "e": 1,
        "emp": "-",
        "cast_time": "5k",
        "duration": "5perc/Tsz",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Az élet szava",
        "mp": 40,
        "e": 1,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Életelementál idézése",
        "mp": 50,
        "e": 1,
        "emp": "-",
        "cast_time": "10k",
        "duration": "1perc/Tsz",
        "range": "3m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Hazatérés",
        "mp": 55,
        "e": 10,
        "emp": "2/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "Önmaga",
        "me_type": "Térmágia",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Élet"
    },
    {
        "spell": "Az élet köre",
        "mp": 70,
        "e": 1,
        "emp": "-",
        "cast_time": "1ó",
        "duration": "10nap/Tsz",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Feltámasztás",
        "mp": "Spec",
        "e": 1,
        "emp": "-",
        "cast_time": "",
        "duration": "",
        "range": "Érintés",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Gólem teremtés (élet)",
        "mp": 90,
        "e": "-",
        "emp": "-",
        "cast_time": "1 nap",
        "duration": "maradandó",
        "range": "érintés",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Kitörlés",
        "mp": 17,
        "e": 1,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Gyógyító eső",
        "mp": "Spec",
        "e": 1,
        "emp": "-",
        "cast_time": "Spec",
        "duration": "Egyszeri",
        "range": "15m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Mérgek kipurgálása",
        "mp": 30,
        "e": 1,
        "emp": "-",
        "cast_time": "3sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Űzés-túlvilági lények",
        "mp": 15,
        "e": 1,
        "emp": "-",
        "cast_time": "3sz",
        "duration": "1óra/Tsz",
        "range": "20m",
        "me_type": "Speciális",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Az élet diadala",
        "mp": 120,
        "e": 1,
        "emp": "-",
        "cast_time": "3sz",
        "duration": "Egyszeri",
        "range": "15m",
        "me_type": "",
        "arcanum": "kis arkánum",
        "type": "rituáléi",
        "sphere": "Élet"
    },
    {
        "spell": "Mentálpillantás",
        "mp": 4,
        "e": 30,
        "emp": 44228,
        "cast_time": "1k",
        "duration": "1perc",
        "range": "Érintés",
        "me_type": "Mentál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Asztrálpillantás",
        "mp": 4,
        "e": 30,
        "emp": 44228,
        "cast_time": "1k",
        "duration": "1perc",
        "range": "Érintés",
        "me_type": "Asztrál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Kétkedés",
        "mp": 3,
        "e": 5,
        "emp": "1,5/1",
        "cast_time": "1sz",
        "duration": "6kör",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Jellem érzékelés",
        "mp": 2,
        "e": 3,
        "emp": "1/2",
        "cast_time": "1k",
        "duration": "1perc",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Meggyőzés",
        "mp": 4,
        "e": 10,
        "emp": "1/2",
        "cast_time": "3sz",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Parancs",
        "mp": 8,
        "e": 10,
        "emp": "1/1",
        "cast_time": "2sz",
        "duration": "1kör/Tsz",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Rettegés",
        "mp": 8,
        "e": 2,
        "emp": "1/1",
        "cast_time": "2sz",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "Asztrál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Érzékelés – hazugság",
        "mp": 8,
        "e": 5,
        "emp": "1/1",
        "cast_time": "3sz",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Fanatizálás",
        "mp": "Spec.",
        "e": 100,
        "emp": "-",
        "cast_time": "1p",
        "duration": "5perc/Tsz",
        "range": "20m",
        "me_type": "-",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Fájdalom",
        "mp": 1,
        "e": 10,
        "emp": "1/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Álomút",
        "mp": 35,
        "e": 1,
        "emp": "-",
        "cast_time": "6k",
        "duration": "15perc",
        "range": "Önmaga",
        "me_type": "",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Bénítás",
        "mp": 15,
        "e": 1,
        "emp": "1/1",
        "cast_time": "1sz",
        "duration": "1kör/Tsz",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Fájdalomcsillapítás",
        "mp": 7,
        "e": 25,
        "emp": "1/2",
        "cast_time": "1p",
        "duration": "1óra/Tsz",
        "range": "Érintés",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Igaz szó",
        "mp": 33,
        "e": 20,
        "emp": "1/1",
        "cast_time": "1k",
        "duration": "5perc/Tsz",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Szférák zenéje",
        "mp": 18,
        "e": 1,
        "emp": "-",
        "cast_time": "10k",
        "duration": "1óra",
        "range": "20m",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Intő jel",
        "mp": 25,
        "e": 3,
        "emp": "2/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Őrző aura",
        "mp": 20,
        "e": 25,
        "emp": "1/1",
        "cast_time": "1p",
        "duration": "1óra/Tsz",
        "range": "Érintés",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Hősi lélek",
        "mp": 40,
        "e": 1,
        "emp": "-",
        "cast_time": "3sz",
        "duration": "1kör/Tsz",
        "range": "Érintés",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Hazugság",
        "mp": 8,
        "e": 5,
        "emp": "1/1",
        "cast_time": "3sz",
        "duration": "1perc/Tsz",
        "range": "Érintés",
        "me_type": "Spec",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Útmutatás",
        "mp": 22,
        "e": 5,
        "emp": "2/1",
        "cast_time": "1p",
        "duration": "10perc/Tsz",
        "range": "50km/Tsz",
        "me_type": "Mentál",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Hang",
        "mp": 12,
        "e": 6,
        "emp": "2/1",
        "cast_time": "2k",
        "duration": "2kör",
        "range": "Végtelen",
        "me_type": "Mentál",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Űzés-evilági lények",
        "mp": 35,
        "e": 20,
        "emp": "2/1",
        "cast_time": "1sz",
        "duration": "24nap",
        "range": "20m",
        "me_type": "Asztrál",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Lélekfátyol",
        "mp": 15,
        "e": "3/Tsz",
        "emp": "-",
        "cast_time": "3sz",
        "duration": "2perc/Tsz",
        "range": "Érintés",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Asztrálpöröly",
        "mp": 17,
        "e": "3/Tsz",
        "emp": "-",
        "cast_time": "1sz",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Mentálpöröly",
        "mp": 17,
        "e": "3/Tsz",
        "emp": "-",
        "cast_time": "1sz",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Láthatatlanság felfedezése",
        "mp": 8,
        "e": 5,
        "emp": "1,5/1",
        "cast_time": "2sz",
        "duration": "12perc",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Lélekelementál idézése",
        "mp": 40,
        "e": 200,
        "emp": "-",
        "cast_time": "10p",
        "duration": "5p/Tsz",
        "range": "5m",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Téboly",
        "mp": 45,
        "e": 10,
        "emp": "3/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Asztrál",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Őrület gyógyítása",
        "mp": 35,
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "Egyszeri",
        "range": "Érintés",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "litániái",
        "sphere": "Lélek"
    },
    {
        "spell": "Asztrális viadal",
        "mp": "",
        "e": "",
        "emp": "",
        "cast_time": "",
        "duration": "",
        "range": "",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Mentális viadal",
        "mp": "",
        "e": "",
        "emp": "",
        "cast_time": "",
        "duration": "",
        "range": "",
        "me_type": "",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Poklok kínjai",
        "mp": 30,
        "e": 5,
        "emp": "2/1",
        "cast_time": "1sz",
        "duration": "5kör",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Összetartozás asztrálisan",
        "mp": "40+spec",
        "e": 1,
        "emp": "-",
        "cast_time": "5p",
        "duration": "1óra/3Tsz",
        "range": "5m/1Km",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Összetartozás mentálisan",
        "mp": "40+spec",
        "e": 1,
        "emp": "-",
        "cast_time": "5p",
        "duration": "1óra/3Tsz",
        "range": "5m/1Km",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Lélekcsapda",
        "mp": 35,
        "e": 1,
        "emp": "-",
        "cast_time": "1k",
        "duration": "5év/Tsz*",
        "range": "20m",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Lélekfaló",
        "mp": 50,
        "e": 15,
        "emp": "3/1",
        "cast_time": "3k",
        "duration": "1nap/Tsz",
        "range": "20m",
        "me_type": "Mentál és Asztrál",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Egyesülés",
        "mp": 120,
        "e": 1,
        "emp": "-",
        "cast_time": "1óra",
        "duration": "2óra/Tsz",
        "range": "Érintés/ Végtelen",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Lélek"
    },
    {
        "spell": "Csapás",
        "mp": 4,
        "e": 1,
        "emp": "4/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "SFÉ",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Méregérzékelés",
        "mp": 5,
        "e": 15,
        "emp": "1/1",
        "cast_time": "2k",
        "duration": "Egyszeri",
        "range": "5m",
        "me_type": "Lepl E",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Élelemteremtés",
        "mp": 7,
        "e": 1,
        "emp": "-",
        "cast_time": "1k",
        "duration": "Egyszeri",
        "range": "Érintés",
        "me_type": "Spec.",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Csend",
        "mp": 8,
        "e": 5,
        "emp": "-",
        "cast_time": "2sz",
        "duration": "1perc/Tsz",
        "range": "Érintés",
        "me_type": "Hangmágia",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Méreg elkészítése",
        "mp": 8,
        "e": 1,
        "emp": "-",
        "cast_time": "10p",
        "duration": "Egyszeri",
        "range": "Érintés",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Vízfakasztás",
        "mp": 8,
        "e": 5,
        "emp": "-",
        "cast_time": "4k",
        "duration": "3kör/Tsz",
        "range": "érintés",
        "me_type": "Spec.",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Láthatatlanság evilági lények elől",
        "mp": 10,
        "e": 5,
        "emp": "2/1",
        "cast_time": "2sz",
        "duration": "5perc/Tsz",
        "range": "Érintés",
        "me_type": "Láthatatlanság",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Vízlégzés",
        "mp": 21,
        "e": 1,
        "emp": "-",
        "cast_time": "6sz",
        "duration": "1perc/Tsz",
        "range": "Önmaga",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Élőlény megkeresése",
        "mp": 6,
        "e": 1,
        "emp": "1/1",
        "cast_time": "1p",
        "duration": "5perc/Tsz",
        "range": "1Km*",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Tájékozódás",
        "mp": 7,
        "e": 1,
        "emp": "-",
        "cast_time": "1k",
        "duration": "10perc/Tsz",
        "range": "Önmaga",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Barátság állatokkal",
        "mp": 10,
        "e": 5,
        "emp": "1,5/1",
        "cast_time": "1k",
        "duration": "5perc/Tsz",
        "range": "Önmaga",
        "me_type": "Asztrál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Köd felidézése",
        "mp": 10,
        "e": 5,
        "emp": "-",
        "cast_time": "4sz",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "Időjárás",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Beszéd állatokkal",
        "mp": 15,
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "5perc/Tsz",
        "range": "Önmaga",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Regeneráció",
        "mp": 15,
        "e": 1,
        "emp": "-",
        "cast_time": "1p",
        "duration": "1óra/Tsz*",
        "range": "Érintés",
        "me_type": "-",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Vadak szólítása",
        "mp": 15,
        "e": 5,
        "emp": "1/1",
        "cast_time": "14k",
        "duration": "Egyszeri",
        "range": "2Km",
        "me_type": "Mentál",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Villámcsapás",
        "mp": 18,
        "e": 3,
        "emp": "6/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Villám",
        "arcanum": "Kis arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Szent tűz",
        "mp": 36,
        "e": 6,
        "emp": "6/1",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Tűz",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Engedelmesség növények",
        "mp": 5,
        "e": 1,
        "emp": "-",
        "cast_time": "2k",
        "duration": "1Perc/Tsz",
        "range": "20m",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "Litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Elemi védelem",
        "mp": 10,
        "e": 1,
        "emp": "10/1",
        "cast_time": "1sz",
        "duration": "1perc/Tsz*",
        "range": "Érintés",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "Litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Szétzúzás",
        "mp": 15,
        "e": 25,
        "emp": "-",
        "cast_time": "1sz",
        "duration": "Egyszeri",
        "range": "20m",
        "me_type": "Természetes anyagok mágiája",
        "arcanum": "Nagy arkánum",
        "type": "Litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Engedelmesség állatok",
        "mp": 15,
        "e": 5,
        "emp": "1/2",
        "cast_time": "2k",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "Mentál",
        "arcanum": "Nagy arkánum",
        "type": "Litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Élőlény megidézése",
        "mp": 19,
        "e": 1,
        "emp": "1/1",
        "cast_time": "2k",
        "duration": "Egyszeri",
        "range": "100Km",
        "me_type": "Mentál, Térmágia",
        "arcanum": "Nagy arkánum",
        "type": "Litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Vihar",
        "mp": 27,
        "e": 15,
        "emp": "-",
        "cast_time": "25p",
        "duration": "1óra",
        "range": "1km",
        "me_type": "Időjárás",
        "arcanum": "Nagy arkánum",
        "type": "Litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Elemi lények szólítása",
        "mp": 35,
        "e": 25,
        "emp": "1/1",
        "cast_time": "10k",
        "duration": "10kör/Tsz",
        "range": "5m",
        "me_type": "Térmágia",
        "arcanum": "Nagy arkánum",
        "type": "Litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Égi szekér",
        "mp": 65,
        "e": 35,
        "emp": "1/1",
        "cast_time": "6k",
        "duration": "15perc/Tsz",
        "range": "5m",
        "me_type": "Térmágia",
        "arcanum": "Nagy arkánum",
        "type": "Litániái",
        "sphere": "Természet"
    },
    {
        "spell": "Természet megidézése",
        "mp": 60,
        "e": 5,
        "emp": "-",
        "cast_time": "2k",
        "duration": "3k/Tsz",
        "range": "15m",
        "me_type": "-",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Földrengés",
        "mp": 80,
        "e": 50,
        "emp": "-",
        "cast_time": "40k",
        "duration": "5perc/Tsz",
        "range": "5km",
        "me_type": "Időjárás",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Őselemek felidézése",
        "mp": 85,
        "e": 60,
        "emp": "1/1",
        "cast_time": "10k",
        "duration": "1perc/Tsz",
        "range": "-",
        "me_type": "Térmágia",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Síkkapu",
        "mp": 95,
        "e": 65,
        "emp": "1/1",
        "cast_time": "30k",
        "duration": "1perc/Tsz",
        "range": "20m",
        "me_type": "Térmágia",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Őselemek uralma",
        "mp": 135,
        "e": 100,
        "emp": "1/1",
        "cast_time": "10k",
        "duration": "1perc/Tsz",
        "range": "-",
        "me_type": "Térmágia",
        "arcanum": "Nagy arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    },
    {
        "spell": "Időjárás ellenőrzése",
        "mp": "55, 100",
        "e": 65,
        "emp": "-",
        "cast_time": "24k",
        "duration": "3perc/Tsz",
        "range": "2km",
        "me_type": "Időjárás",
        "arcanum": "arkánum",
        "type": "rituáléi",
        "sphere": "Természet"
    }
]